# Data Analytics with Python

## Header
The header of each notebook or skript imports the packages used below. There are common abbreviations for each package, which I higly recommend to use for readability. Keywords of python are always marked in a different color than the usual code. Python doesn't allow using these words as variables.

In [1]:
import numpy as np
import pandas as pd

## Simple calculations and basic expressions
You can use jupyter notebooks as an advanced calculator.

In [352]:
a = 3 * (2 + 2)
a

12

In [353]:
b = 625 ** 0.5
b

25.0

There are four kinds of variables: **Integer**, **Floats** for numbers, **strings** for text and **bool** for True/False claims. 

In [354]:
c = 'Hello world'
c

'Hello world'

In [355]:
d = 'i' in 'string'
d

True

In [356]:
type(a), type(b), type(c), type(d)

(int, float, str, bool)

## More complex objects and loops
### Lists
Lists are a collection of variables indexed from zero onwards. If you want to find out more features of this object, please refer to https://docs.python.org/3/tutorial/datastructures.html .

In [357]:
# Lists
list_1 = [1, 2, True, 4, 'string', [1, 2, 5]]
list_1

[1, 2, True, 4, 'string', [1, 2, 5]]

In [358]:
for i, j in enumerate(list_1):
    print(i, j)

0 1
1 2
2 True
3 4
4 string
5 [1, 2, 5]


In [359]:
list_1[5]

[1, 2, 5]

In [360]:
list_1[2:4]

[True, 4]

In [342]:
# List with the first 20 quadratic numbers
quad = []
for i in range(0, 20):
    quad.append(i ** 2)
quad[15:18]

[225, 256, 289]

In [93]:
j = len(quad) - 1
while j >= 0:
    print(np.sqrt(quad[j]))
    j = j - 1

19.0
18.0
17.0
16.0
15.0
14.0
13.0
12.0
11.0
10.0
9.0
8.0
7.0
6.0
5.0
4.0
3.0
2.0
1.0
0.0


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [341]:
for i in quad:
    print(np.sqrt(i))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0


In [373]:
numbers = np.sqrt(quad)
numbers

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [ ]:
c.split()

### Dictionaries
Dictionaries are basically mappings from a key value to any other object. Find out more on https://docs.python.org/3/tutorial/datastructures.html#dictionaries

In [95]:
results = {'int': a, 'float': b, 'string': c, 'bool': d, 'Quadratic Numbers': quad, 'Roots': numbers}
results

{'Quadratic Numbers': [0,
  1,
  4,
  9,
  16,
  25,
  36,
  49,
  64,
  81,
  100,
  121,
  144,
  169,
  196,
  225,
  256,
  289,
  324,
  361],
 'Roots': array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.]),
 'bool': True,
 'float': 25.0,
 'int': 12,
 'string': 'Hello world'}

In [108]:
results['Roots']

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [339]:
for i in results:
    print(results[i])

Hello world
True
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
12
25.0
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [54]:
population_dict = {
    'California': 38332521,
    'Florida': 19552869,
    'Illinois': 12882135
}

In [109]:
population_dict['California']

38332521

## Introducing pandas

This is just a short introduction and doesn't cover at all the features Pandas has. Here is the link to the documentation:
https://pandas.pydata.org/pandas-docs/stable/index.html

### pandas Series



In [100]:
data = pd.Series([1,2], index = ['a', 'b'])

In [103]:
data.index

Index(['a', 'b'], dtype='object')

In [105]:
population = pd.Series(population_dict)
population

California    38332521
Florida       19552869
Illinois      12882135
dtype: int64

In [106]:
population['California']

38332521

### pandas DataFrame
DataFrames are the main object for storing data. It is a main advantage of python to be able to handle several datasets at once.

In [124]:
area_dict = {
    'California': 423967,
    'Florida': 170312,
    'Illinois': 149995
}
area = pd.Series(area_dict)

In [125]:
area

California    423967
Florida       170312
Illinois      149995
dtype: int64

In [237]:
states = pd.DataFrame({'population': population, 'area': area})

In [238]:
states

area  population
California  423967    38332521
Florida     170312    19552869
Illinois    149995    12882135

In [239]:
states.index

Index(['California', 'Florida', 'Illinois'], dtype='object')

In [240]:
states.columns

Index(['area', 'population'], dtype='object')

In [241]:
states['area']

California    423967
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [242]:
states.area

California    423967
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [243]:
states['density'] = states['population'] / states['area']

In [244]:
states['country'] = 'USA'

In [245]:
states[states.density > 100]

area  population     density country
Florida  170312    19552869  114.806173     USA

## Combining DataFrames
We are going to look at several methods to combine DataFrames. These methods reach from simple DataFrame stacking, to more advanced merge commands.

In [375]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
df3 = pd.DataFrame({'employer_group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

In [376]:
df1 

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [377]:
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [378]:
pd.concat([df1, df2], axis=1).drop('employee', axis=1)

group  hire_date
0   Accounting       2004
1  Engineering       2008
2  Engineering       2012
3           HR       2014

In [312]:
pd.merge(df1,df2)

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [313]:
df3

employer_group supervisor
0     Accounting      Carly
1    Engineering      Guido
2             HR      Steve

In [316]:
df4 = pd.merge(df1, df3, left_on = 'group', right_on = 'employer_group')

In [317]:
df4.drop('group', axis = 1)

employee employer_group supervisor
0      Bob     Accounting      Carly
1     Jake    Engineering      Guido
2     Lisa    Engineering      Guido
3      Sue             HR      Steve

## Application
I am now going to show you how to apply the methods we just saw on [John Rust (1987): Optimal Replacement of GMC Bus Engines: An Empirical Model of Harold Zurcher](https://doi.org/10.2307/1911259) to replicate the first descriptive table in the paper. The data can be found and downloaded on https://editorialexpress.com/jrust/nfxp.html. There you also find the readme and the documentation, where I got the information, which is stored in the following two dictionaires. The methods used are all introduced above or can be looked up in the provided links.

In [318]:
dict_data = {'g870': [36, 15, 'Group 1'], 'rt50': [60, 4, 'Group 2'],
             't8h203': [81, 48, 'Group 3'], 'a452372': [137, 18, 'Group 8'],
             'a452374': [137, 10, 'Group 6'], 'a530872': [137, 18, 'Group 7'],
             'a530874': [137, 12, 'Group 5'], 'a530875': [128, 37, 'Group 4']}
re_col = {1: 'Bus_ID', 2: "Month_pur", 3: "Year_pur", 4: "Month_1st", 5: "Year_1st", 6: "Odo_1st",
          7: "Month_2nd", 8: "Year_2nd", 9: "Odo_2nd", 10: "Month_begin", 11: "Year_begin"}

In [333]:
dict_df = {}
for keys in dict_data:
    r = dict_data[keys][0]
    c = dict_data[keys][1]
    f_raw = open('data/' + keys + '.asc').read()
    f_col = f_raw.split('\n')
    df = pd.DataFrame()
    for j in range(0, c):
        for k in range(j * r, (j + 1) * r):
            df.loc[(k - j * r) + 1, j + 1] = float(f_col[k])
    df = df.transpose()
    df = df.rename(columns=re_col)
    df['Bus_ID'] = df['Bus_ID'].astype(str)
    df = df.set_index('Bus_ID')
    dict_df[dict_data[keys][2]] = df

In [372]:
df = pd.DataFrame()
for j, i in enumerate(sorted(dict_df.keys())):
    df2 = dict_df[i][['Odo_1st']][dict_df[i]['Odo_1st'] > 0]
    df2 = df2.rename(columns={'Odo_1st': i})
    df3 = dict_df[i][['Odo_2nd']].sub(dict_df[i]['Odo_1st'], axis=0)[dict_df[i]['Odo_2nd'] > 0]
    df3 = df3.rename(columns={'Odo_2nd': i})
    df3 = df3.set_index(df3.index + '_2')
    df4 = pd.concat([df2, df3])
    if j == 0:
        df = df4.describe()
    else:
        df = pd.concat([df, df4.describe()], axis=1)
df = df.transpose()
df = df.drop(df.columns[[4, 5, 6]], axis=1)
df[['max', 'min', 'mean', 'std', 'count']].fillna(0).astype(int)

max     min    mean    std  count
Group 1       0       0       0      0      0
Group 2       0       0       0      0      0
Group 3  273400  124800  199733  37459     27
Group 4  387300  121300  257336  65477     33
Group 5  322500  118000  245290  60257     11
Group 6  237200   82400  150785  61006      7
Group 7  331800  121000  208962  48980     27
Group 8  297500  132000  186700  43956     19